######################################################################
# Automatically generated by qmake (3.0) mer. nov. 2 14:33:45 2016
######################################################################

TEMPLATE += app
TARGET = nav
INCLUDEPATH += .

DESTDIR = build/
OBJECTS_DIR = build/
MOC_DIR = build/
RCC_DIR = build/
UI_DIR = build/

QT += widgets core gui webkitwidgets

# Input
HEADERS += bookmark.h primaryWindow.h bookmark.cpp
SOURCES += bookmark.cpp main.cpp primaryWindow.cpp
